name: Blank Workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world!"
  test1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test after build
        run: echo "after build"
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: test in parallel with build
        run: echo "parallel with build"